keys() 딕셔너리 내의 모든 키를 반환
values() 딕셔너리 내의 모든 값을 반환
items() 딕셔너리 내의 모든 항목을 [키]:[값] 쌍으로 반환

10.1
넘파이(numpy):리스트에 비하여 처리속도가 매우 빠름데이터 분석의 위한 패키지인 판다스(Pandas)
10.2
넘파이는 성능이 우수한 ndarray객체를 제공
ndarray는 n차원 배열을 의미=다차원배열
ndarray 객체가 가진 장점
- ndaaray는 c언어에 기반한 배열 구조이므로 메모리를 적게 차지하고 속도가 빠름
- ndarray를 사용하면 배열과 배열 간에 수학적인 연산을 적용할 수 있다.
- ndarray는 고급 연산자와 풍부한 함수들을 제공
10.3
넘파이 패키지를 불러오는 코드 호출
- import numpy as np
array()함수 : 넘파이 배열을 만들때 제공하는 함수

In [1]:
#도전문제10.1
import numpy as np
a = np.array(range(1, 11))
b = np.array(range(10, 101, 10))

a + b, a-b, a * b, a / b

(array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110]),
 array([ -9, -18, -27, -36, -45, -54, -63, -72, -81, -90]),
 array([  10,   40,   90,  160,  250,  360,  490,  640,  810, 1000]),
 array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]))

10.4
ndim : 배열 축 혹은 차원의 개수
shape : 배열의 차원으로 (m,n)형식의 튜플형이다.
size : 배열 원소의 개수
dtype : 배열내의 원소의 형을 기술하는 객체이다.
itemsize : 배열내의 원소의 크기를 바이트 단위로 기술한다.
data : 배열의 실제 원소를 포함하고 있는 버퍼
stride : 배열 각 차원별로 다음 요소로 점프하는 데에 필요한 거리를 바이트로 표시한 값을 모은 튜플

In [40]:
#도전문제10.2
a = np.array(range(1, 11)) + np.array(range(10, 101, 10))
print(a.shape)
print(a.size)

(10,)
10


In [43]:
#실습10.1
import numpy as np

array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("실습 1 : array_a =", array_a)

array_b = np.array(range(10))
print("실습 2 : array_b =", array_b)

array_c = np.array(range(0, 10, 2))
print("실습 3 : array_c =", array_c)

print("실습 4 : ")
print('array_c의 shape :', array_c.shape)
print('array_c의 ndim :', array_c.ndim)
print('array_c의 ctype :', array_c.dtype)
print('array_c의 size :', array_c.size)
print('array_c의 itemsize :', array_c.itemsize)

실습 1 : array_a = [0 1 2 3 4 5 6 7 8 9]
실습 2 : array_b = [0 1 2 3 4 5 6 7 8 9]
실습 3 : array_c = [0 2 4 6 8]
실습 4 : 
array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 ctype : int32
array_c의 size : 5
array_c의 itemsize : 4


In [46]:
#실습10.2
import numpy as np

heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)
bmi = np_weights/(np_heights**2)

print("대상자들의 키 :", np_heights)
print("대상자들의 몸무게 :", np_weights)
print("대상자들의 BMI")
print(bmi)


대상자들의 키 : [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게 : [86 74 59 95 80 68]
대상자들의 BMI
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


10.6
scores = np.array([88, 72, 93, 94, 89, 78, 99])

인덱싱은 특정한 요소를 얻는 방법
score[2]
>>>93

슬라이싱은 요소 집합을 얻는 방법
score[1:4]
>>>[72, 93, 94]

scores[3:]
>>> array([94, 89, 78, 99])

scores[4:-1]
>>> array([89, 78])

10.7
논리적인 인덱싱 : 어떤 조건을 주어서 배열에서 원하는 값을 추려내는 것

ages = np.array([18, 19, 25, 30, 28])
y = ages > 20
print(y)
>>> array([False, False,  True,  True,  True])

ages[ ages > 20 ]
>>> array([25, 30, 28])

10.8
파이썬의 2차원 리스트 : 리스트 안에 다른 리스트가 들어있는 형태
넘파이 2차원배열은 np.array()를 호출하여 생성

import numpy as np
y = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 2차원 배열(리스트 자료형)

np_array = np.array(y) # 2차원 배열(넘파이 다차원 배열)
np_array
>>>
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np_array[0][2]
>> 3

10.9
넘파이의 2차원배열에서 인덱스 표기법 
리스트 스타일 np_array[0][2]
넘파이 스타일 np_array[0, 2]
- 두 스타일 다 사용가능하다
넘파이 배열은 파이썬 리스트와 달리 모든 항목이 동일한 자료형을 가진다.

np_array[2, 2] = 1.234 # 마지막 요소의 값을 실수로 변경하려고 하면 실패
np_array
>>
array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  1]])
자료형이 달라 바뀌지 않는다.

10.10
np_array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

np_array[0:2, 2:4]
>>
array([[3, 4],
       [7, 8]])

print(np_array[::2][::2])
>> [[1 2 3 4]]

print(np_array[::2, ::2])
>>
[[ 1  3]
 [ 9 11]]

10.11
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

np_array > 5
>>
array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

np_array[np_array > 5]
>> array([6, 7, 8, 9])


np_array[:, 2]
>> array([3, 6, 9])

np_array[:, 2] > 5
>> array([False,  True,  True])


np_array[:] % 2 == 0
>>
array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

np_array[np_array % 2 == 0]
>> array([2, 4, 6, 8])

In [47]:
#실습10.3
x = np.array( [['a', 'b', 'c', 'd'], ['c', 'c', 'g', 'h']] )

mat_a = np.array( [[10, 20, 30], [10, 20, 30]] )
mat_b = np.array( [[2, 2, 2], [1, 2, 3]])

print(x [x == 'c'])
print(mat_a - mat_b)

['c' 'c' 'c']
[[ 8 18 28]
 [ 9 18 27]]


10.4
ndim : 배열 축 혹은 차원의 개수
shape : 배열의 차원으로 (m,n)형식의 튜플형이다.
size : 배열 원소의 개수
dtype : 배열내의 원소의 형을 기술하는 객체이다.
itemsize : 배열내의 원소의 크기를 바이트 단위로 기술한다.
data : 배열의 실제 원소를 포함하고 있는 버퍼
stride : 배열 각 차원별로 다음 요소로 점프하는 데에 필요한 거리를 바이트로 표시한 값을 모은 튜플

In [9]:
#실습10.4
import numpy as np

x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73], [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3]
z = x[0:2][1:3]

print("x shape :", x.shape)
print("y shape :", y.shape)
print("z shape :", z.shape)
print("z values :", z)
print("BMI data")
bmi = x[1] / x[0]**2
print(bmi)


x shape : (2, 6)
y shape : (2, 2)
z shape : (1, 6)
z values : [[86. 74. 59. 95. 80. 68.]]
BMI data
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [1]:
#10.5
import numpy as np

players = [[170, 76.4],
           [183, 86.2],
           [181, 78.5],
           [176, 80.1]]

np_players = np.array(players)

print("몸무게가 80 이상인 선수 정보")
print(np_players[np_players[:,1] >= 80.0])
print('키가 180 이상인 선수 정보')
print(np_players[np_players[:,0]>= 180])

몸무게가 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보
[[183.   86.2]
 [181.   78.5]]


10.12
arange()함수 : 특정한 범위의 정수를 가지는 넘파이 배열을 쉽게 만들수 있다
numpy.arange([start], stop, [step])
- start : 데이터 생성을 시작할 값(생략시 0으로 처리됨)
- stop : 데이터 생성을 멈출 값으로 생략할 수 없음 데이터는 stop-1 까지 생성된다
- step : 데이터 생성 간격(생략시 1로 처리됨)

np.array(range(5)) = np.arange(5) = array([0, 1, 2, 3, 4])

import numpy as np
np.arange(5)
>> array([0, 1, 2, 3, 4])

np.array(range(5))
>> array([0, 1, 2, 3, 4])



range(5)
>> range(0, 5)

range(0, 5, 2)
>> range(0, 5, 2)

list(range(5))
>> [0, 1, 2, 3, 4]

10.13
numpy.linspace(start, stop, num=50)
inspace()는 시작값부터 끝값까지 균일한 간격으로 지정된 개수만큼의 배열을 생성한다.
ex) np.linspace(0, 10, 100) # 0에서 10까지 총 100개의 수들이 생성

numpy.logspace(start, stop, num=50)
logspace(x, y, n)
10^x 부터 10^y까지가 되며, n개의 수가 생성

10.14
reshape() 함수는 데이터의 개수는 유지한 채로 배열의 차원과 형태를 변경한다.

import numpy as np
y = np.arange(12)
y
>> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 1차원 배열이 3행 4열의 2차원 배열로 바뀜
y.reshape(3, 4) 
>>
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

만약 인수로 -1을 전달하면 데이터의 개수에 맞춰서 자동으로 배열의 형태가 결정된다.
y.reshape(6, -1)
>>
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])


flatten()은 평탄화 함수로 2차원 이상의 고차원 배열을 1차원 배열로 만들어 준다.
# 2차원 배열을 1차원 배열로 만들어 준다
y.flatten() 
>> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


10.15
난수(random number) 특정한 패턴이 존재하지 않는다는 특징을 가지고 출현하는 수

10.16
시드는 컴퓨터로 만드는 난수의 초기 입력값으로 사용된다. 
넘파이에서 난수의 시드를 설정하는 문장
np.random.seed(100)
의사난수 : 컴퓨터가 규칙을 가지고 생성한 수로 정확한 의미의 난수는 아니지만 난수에 가까운 수

# 10에서 20 사이에 있는 난수 5개를 생성
a = 10
b = 20
(b - a) * np.random.rand(5) + a 
>> array([14.31704184, 19.4002982 , 18.17649379, 13.3611195 , 11.75410454])

1부터 7사이에 난수를 10개
np.random.randint(1, 7, size=10)

4*7인 2차원배열을 1부터 10사이의 정수 난수
np.random.randint(1, 11, size=(4, 7))

10.17
np.random.randn(5)
>> array([-1.02933685, -0.51099219, -2.36027053,  0.10359513,  1.73881773])

# 5행 4열의 난수를 생성
np.random.randn(5, 4)
>>
array([[ 1.24187584,  0.13241276,  0.57779396, -1.57590571],
       [-1.29279424, -0.65991979, -0.87400478, -0.68955061],
       [-0.53547985,  1.52795302,  0.64720579, -0.67733661],
       [-0.2650188 ,  0.74610644, -3.13078483,  0.05962178],
       [-0.87521111,  1.06487833, -0.57315265, -0.80327849]])

# 평균이 10이고 표준편차 값이 2인 정규분포를 가지는 난수
mu = 10
sigma = 2
randoms = mu + sigma * np.random.randn(5, 4)
randoms
>>
array([[12.18594325, 11.30255516, 14.32104958,  8.72173986],
       [ 9.33262494,  9.12479628,  6.18841024,  7.54196134],
       [11.58979772,  7.67898372, 11.09211104, 12.32651667],
       [11.31775404, 11.04737852, 12.65431215, 12.22504894],
       [ 7.85074079, 10.68683233, 11.97087508, 11.47300336]])


10.18

mean() 함수는 넘파이 패키지가 가지고 있는 평균을 계산하는 함수이다.
np.mean(heights)
>> 174.9972570108985

중앙값이란 리스트의 중앙에 있는 항목이다.
np.median(heights)
>> 174.90487455543172


In [18]:
#10.6
import numpy as np

players = np.zeros((100, 3))
players[:, 0] = 10 * np.random.randn(100)+175
players[:, 1] = 10 * np.random.randn(100)+70
players[:, 2] = np.floor(10 * np.random.randn(100))+22

heights = players[:, 0]
print('신장 평균값:', np.mean(heights))
print('신장 중앙값:', np.median(heights))

weights = players[:, 1]
print('체중 평균값:', np.mean(weights))
print('체중 중앙값:', np.median(weights))

ages = players[:, 2]
print('나이 평균값:', np.mean(ages))
print('나이 중앙값:', np.median(ages))



신장 평균값: 174.48848199693887
신장 중앙값: 173.27405126890315
체중 평균값: 68.99349924420262
체중 중앙값: 69.17136363152672
나이 평균값: 22.18
나이 중앙값: 23.0


10.19
corrcoef() 함수가 계산하는 상관관계의 수학적 정의

뭔소린지 모르겠음

10.20

이것도 마찬가지로 모르겠음

핵심정리

넘파이는 리스트가 아니라 배열로 다차원 데이터를 다룬다

배열은 동일한 자료형을 연속해서 가진 데이터 구조로 읽고 쓰는 일을 빠르게 할 수 있다

리스트와 달리 넘파이 배열들을 서로 연산하면 벡터와 행렬처럼 다루어진다

넘파이 배열도 리스트와 다른 반복가능 객체처럼 슬라이싱을 적용할 수 있다

넘파이는 넘파이만의 스타일로 슬라이싱을 할 수 있으며, 리스트 등과 다른 방식의 결과가 나온다

슬라이싱과 별개로 논리적 조건을 부여하여 항목을 가져오는 일도 가능하다